name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey, Nice issue, we might take a while to see this issue, as currently our website is dead.'
        pr-message: 'Hey its great that youre making progress on the website, but do note that there is no actual website'
